---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mitm-proxy
  name: mitm-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mitm-proxy
  template:
    metadata:
      labels:
        app: mitm-proxy
    spec:
      containers:
        - image: mitmproxy/mitmproxy:latest
          name: mitm-proxy
          command:
            - mitmweb
            - --web-host
            - "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mitm-proxy
  name: mitm-proxy
spec:
  selector:
    app: mitm-proxy
  type: NodePort
  ports:
    - name: mitm-web
      port: 8087
      targetPort: 8081
      protocol: TCP
    - name: mitm-wg
      port: 51820
      targetPort: 51820
      protocol: UDP
  externalIPs:
    - 192.168.109.2